### ISSUE TITLE
Analyzer suggests replacing [OrchestrationTrigger] DurableOrchestrationContextBase with [OrchestrationTrigger] DurableOrchestrationContext

### ISSUE THREAD

**Issue by andylholloway** [stimms/DurableFunctionsAnalyzer#10]
Hi
Thanks for this, it's a great idea. 

I've installed the nuget package and got this warning:
`DurableFunctionOrchestrationTriggerAnalyzer OrchestrationTrigger must be attached to a DurableOrchestrationContext`

The analyzer suggests the use of `[OrchestrationTrigger] DurableOrchestrationContextBase` should be replaced with `[OrchestrationTrigger] DurableOrchestrationContext`, but we use the base class to mock the DurableOrchestrationContext.

Is this expected behaviour?

**Comment by stimms** [comment]
First off thank you so much for using the tool. You pose a great question and now I have to think about how opinionated I want to be. Personally, I think the additional surface area of the DurableOrchestrationContext makes it a better candidate for triggering functions than DurableOrchestrationContextBase. However, it feels too restrictive of me to prevent people from using the more limited surface area of the Base class if they can get away with it. What you're going to get in the function is a DurableOrchestrationContext as DurableOrchestrationContextBase is abstract. 

I'm going to relax that restriction and allow DurableOrchestrationContextBase.
